### ISSUE TITLE
Example doesn't seem to work on iOS 8 beta

### ISSUE THREAD

**Issue by chamrc** [deepan/DSNestedAccordion#1]
[Imgur](http://i.imgur.com/0TVtr8v.png)

**Comment by deepan** [comment]
Can you help me to reproduce the issue ? 

I have verified that the example works fine on Xcode Version 6.0 (6A215l) & iOS simulator  - iPhone 5s / iOS 8.0 (12A4265u)

**Comment by chamrc** [comment]
That was beta 4 or 5, it's working now. Closing the issue.
