### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by Stan92** [deepan/DSNestedAccordion#5]
Hello,
I've a UViewController that hosts a tableview, and additional UILabel, UIButton, etc...
How can I set the DSNestedAccordionHandler into the interface?
Or how can I tell the UITableview should use the delegate and datasource coming from the handler?
I don't know if I m clear about my query.

**Comment by faceleg** [comment]
Have you had a look into the example app?

**Comment by Stan92** [comment]
Yes I did (but after posting the message).. 
Thanks.. this conversation must be closed :) even deleted :)
